# Site settings
email: choongwon.kr@gmail.com
paginate: 8
paginate_path: "/page-:num/"
google_analytics:
enable_disqus: true
disqus_shortname: leechoong

# SEO settings
title: 리충닷컴
description: 공부하는 블로그
url: "https://leechoongwon.github.io"
# twitter_username:
default_img:

# Profile settings
name:
profile_img: /assets/img/me.jpeg
profile: ""
social:
  github: https://github.com/leechoong

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /posts/:year/:title

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
