# Site settings
email:
paginate: 8
paginate_path: "/blog/page-:num"
timezone: Asia/Seoul

# SEO settings
title: 리충 테스트
description: 테스트중
url: "https://leechoongwon.github.io"
default_img: ""

# Profile settings
name: 테스트
profile_img: ""
profile: ""
social:
  github: ""
  facebook: ""

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

# S3 Img
static_url: ""
