# SITE CONFIGURATION
baseurl: ""
url: "https://leechoongwon.github.io"
permalink: /posts/:year/:title

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: 리충닷컴
  avatar: assets/img/main.png
  favicon: assets/favicon.ico
  description: "나의 관심 블로그"

  # Header and footer text
  header_text: >
     "Have the courage to follow your heart and intuition." <br> ― Steve Jobs
  header_text_feature_image: assets/img/header1.png
  footer_text: >
    Powered by <a href="https://jekyllrb.com/">Jekyll</a> and <a href="https://pages.github.com/">Github Pages</a><br>&copy; 2018. by Lee Choongwon

  # Icons
  rss: true
  email_address: "leechoong.kr@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "leechoong"
  google_plus:
  instagram: "leechoong.kr"
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features
  google_analytics: # Tracking ID
  disqus_shortname: leechoong
  katex: true # Enable if using math markup
  portfolio: true
  search: true
  categories: true


  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Read more"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  google_fonts: # "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 6
paginate_path: "/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: ["Gemfile", "Gemfile.lock", "*.gem", "LICENSE", "README.md"]
